# Generated by Django 2.1.1 on 2018-11-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='scraped_completion',
            field=models.IntegerField(default=0),
        ),
    ]
