# Generated by Django 2.1.1 on 2018-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0003_auto_20181124_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='topic_distributions',
            field=models.TextField(),
        ),
    ]
