# Generated by Django 2.1.1 on 2018-12-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0006_review_topics_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='topics_completion',
            field=models.IntegerField(default=0),
        ),
    ]
