# Generated by Django 2.1.1 on 2018-12-09 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0007_film_topics_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_polarity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
