# Generated by Django 2.1.1 on 2018-12-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0008_review_sentiment_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='polarities_binned',
            field=models.TextField(default=''),
        ),
    ]
