# Generated by Django 2.1.1 on 2018-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0011_review_cached_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='manually_flagged_as_shady',
            field=models.BooleanField(default=False),
        ),
    ]
