prefix = "."
dataset = "manually_tagged_backhanded"
corpus = "line.toml"
index = "manually_tagged_backhanded-idx"
stop-words = "manually_tagged_backhanded-stopwords.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[[classifier]]
method = "one-vs-all"
    [classifier.base]
    method = "sgd"
    loss = "hinge"
